# ОСНОВЫ  SQL

Для выполнения SQL запросов осуществим подключение к учебной базе данных chinook.db. Это один из способов подключения.

In [4]:
list()

[]

In [2]:
# импортируем модуль sqlite3 для работы с базой данных SQL
import sqlite3 as sql
import pandas as pd
 
# создадим соединение с базой данных chinook
connect = sql.connect('chinook.db')
 
# выберем все строки из таблицы tracks
sql_data = pd.read_sql('SELECT * FROM tracks;', connect) 
 
# посмотрим на результат
sql_data


TrackId                                               Name  AlbumId  \
0           1            For Those About To Rock (We Salute You)        1   
1           2                                  Balls to the Wall        2   
2           3                                    Fast As a Shark        3   
3           4                                  Restless and Wild        3   
4           5                               Princess of the Dawn        3   
...       ...                                                ...      ...   
3498     3499  Pini Di Roma (Pinien Von Rom) \ I Pini Della V...      343   
3499     3500  String Quartet No. 12 in C Minor, D. 703 "Quar...      344   
3500     3501               L'orfeo, Act 3, Sinfonia (Orchestra)      345   
3501     3502  Quintet for Horn, Violin, 2 Violas, and Cello ...      346   
3502     3503                                      Koyaanisqatsi      347   

      MediaTypeId  GenreId                                           Composer  \
0               1        1          Angus Young, Malcolm Young, Brian Johnson   
1               2        1                                               None   
2               2        1  F. Baltes, S. Kaufman, U. Dirkscneider & W. Ho...   
3               2        1  F. Baltes, R.A. Smith-Diesel, S. Kaufman, U. D...   
4               2        1                         Deaffy & R.A. Smith-Diesel   
...           ...      ...                                                ...   
3498            2       24                                               None   
3499            2       24                                     Franz Schubert   
3500            2       24                                 Claudio Monteverdi   
3501            2       24                            Wolfgang Amadeus Mozart   
3502            2       10                                       Philip Glass   

      Milliseconds     Bytes  UnitPrice  
0           343719  11170334       0.99  
1           342562   5510424       0.99  
2           230619   3990994       0.99  
3           252051   4331779       0.99  
4           375418   6290521       0.99  
...            ...       ...        ...  
3498        286741   4718950       0.99  
3499        139200   2283131       0.99  
3500         66639   1189062       0.99  
3501        221331   3665114       0.99  
3502        206005   3305164       0.99  

[3503 rows x 9 columns]

In [3]:
invoices = pd.read_sql('SELECT * FROM invoices;', connect) 
invoices

InvoiceId  CustomerId          InvoiceDate  \
0            1           2  2009-01-01 00:00:00   
1            2           4  2009-01-02 00:00:00   
2            3           8  2009-01-03 00:00:00   
3            4          14  2009-01-06 00:00:00   
4            5          23  2009-01-11 00:00:00   
..         ...         ...                  ...   
407        408          25  2013-12-05 00:00:00   
408        409          29  2013-12-06 00:00:00   
409        410          35  2013-12-09 00:00:00   
410        411          44  2013-12-14 00:00:00   
411        412          58  2013-12-22 00:00:00   

                               BillingAddress BillingCity BillingState  \
0                     Theodor-Heuss-Straße 34   Stuttgart         None   
1                            Ullevålsveien 14        Oslo         None   
2                             Grétrystraat 63    Brussels         None   
3                              8210 111 ST NW    Edmonton           AB   
4                             69 Salem Street      Boston           MA   
..                                        ...         ...          ...   
407                     319 N. Frances Street     Madison           WI   
408                    796 Dundas Street West     Toronto           ON   
409  Rua dos Campeões Europeus de Viena, 4350       Porto         None   
410                           Porthaninkatu 9    Helsinki         None   
411                       12,Community Centre       Delhi         None   

    BillingCountry BillingPostalCode  Total  
0          Germany             70174   1.98  
1           Norway              0171   3.96  
2          Belgium              1000   5.94  
3           Canada           T6G 2C7   8.91  
4              USA              2113  13.86  
..             ...               ...    ...  
407            USA             53703   3.96  
408         Canada           M6J 1V1   5.94  
409       Portugal              None   8.91  
410        Finland             00530  13.86  
411          India            110017   1.99  

[412 rows x 9 columns]

С целью минимизации кода создадим функцию, которая будет возвращать объект DataFrame, принимая строку с SQL запросом.

In [4]:
def request(str):
    return pd.read_sql('''{}'''.format(str), connect)

Далее сконцентрируемся уже на SQL- запросах. 

Получите все записи из таблицы genres

In [7]:
request('''
SELECT *
FROM genres;
''')

GenreId                Name
0         1                Rock
1         2                Jazz
2         3               Metal
3         4  Alternative & Punk
4         5       Rock And Roll
5         6               Blues
6         7               Latin
7         8              Reggae
8         9                 Pop
9        10          Soundtrack
10       11          Bossa Nova
11       12      Easy Listening
12       13         Heavy Metal
13       14            R&B/Soul
14       15   Electronica/Dance
15       16               World
16       17         Hip Hop/Rap
17       18     Science Fiction
18       19            TV Shows
19       20    Sci Fi & Fantasy
20       21               Drama
21       22              Comedy
22       23         Alternative
23       24           Classical
24       25               Opera

Для работы с базой данных необходимо понимать структуру базы данных или  схему базы данных.

![](https://raw.githubusercontent.com/vkv82/Lesson/refs/heads/main/sql_lite.jpg)

Задание
 Получите все записи из таблицы invoices, оставив только 5 строк, начиная с шестой  строки.

In [13]:
request('''
SELECT *
FROM invoices
LIMIT 5
OFFSET 6''')

InvoiceId  CustomerId          InvoiceDate          BillingAddress  \
0          7          38  2009-02-01 00:00:00     Barbarossastraße 19   
1          8          40  2009-02-01 00:00:00          8, Rue Hanovre   
2          9          42  2009-02-02 00:00:00  9, Place Louis Barthou   
3         10          46  2009-02-03 00:00:00        3 Chatham Street   
4         11          52  2009-02-06 00:00:00       202 Hoxton Street   

  BillingCity BillingState  BillingCountry BillingPostalCode  Total  
0      Berlin         None         Germany             10779   1.98  
1       Paris         None          France             75002   1.98  
2    Bordeaux         None          France             33000   3.96  
3      Dublin       Dublin         Ireland              None   5.94  
4      London         None  United Kingdom            N1 5LH   8.91

In [14]:
request('''
SELECT *
FROM invoices
LIMIT 5
OFFSET 6; 
''')

InvoiceId  CustomerId          InvoiceDate          BillingAddress  \
0          7          38  2009-02-01 00:00:00     Barbarossastraße 19   
1          8          40  2009-02-01 00:00:00          8, Rue Hanovre   
2          9          42  2009-02-02 00:00:00  9, Place Louis Barthou   
3         10          46  2009-02-03 00:00:00        3 Chatham Street   
4         11          52  2009-02-06 00:00:00       202 Hoxton Street   

  BillingCity BillingState  BillingCountry BillingPostalCode  Total  
0      Berlin         None         Germany             10779   1.98  
1       Paris         None          France             75002   1.98  
2    Bordeaux         None          France             33000   3.96  
3      Dublin       Dublin         Ireland              None   5.94  
4      London         None  United Kingdom            N1 5LH   8.91

**СРЕЗЫ ДАННЫХ**

Найдем все записи в таблице tracks, UnitPrice которых больше 1.

In [15]:
request('''
SELECT * 
FROM tracks
WHERE unitprice > 1;
''')

TrackId                                    Name  AlbumId  MediaTypeId  \
0       2819  Battlestar Galactica: The Story So Far      226            3   
1       2820                  Occupation / Precipice      227            3   
2       2821                           Exodus, Pt. 1      227            3   
3       2822                           Exodus, Pt. 2      227            3   
4       2823                           Collaborators      227            3   
..       ...                                     ...      ...          ...   
208     3362       There's No Place Like Home, Pt. 1      261            3   
209     3363       There's No Place Like Home, Pt. 2      261            3   
210     3364       There's No Place Like Home, Pt. 3      261            3   
211     3428                          Branch Closing      251            3   
212     3429                              The Return      251            3   

     GenreId Composer  Milliseconds       Bytes  UnitPrice  
0         18     None       2622250   490750393       1.99  
1         19     None       5286953  1054423946       1.99  
2         19     None       2621708   475079441       1.99  
3         19     None       2618000   466820021       1.99  
4         19     None       2626626   483484911       1.99  
..       ...      ...           ...         ...        ...  
208       21     None       2609526   522919189       1.99  
209       21     None       2497956   523748920       1.99  
210       21     None       2582957   486161766       1.99  
211       22     None       1814855   360331351       1.99  
212       22     None       1705080   343877320       1.99  

[213 rows x 9 columns]

Задание
1. Найдите все записи в таблице tracks, Milliseconds которых меньше 10000
2. Найдите все записи в таблице tracks, Milliseconds которых меньше 10000 и AlbumId равен 18.
3. Найдите все записи  композитора Samuel Rosa.
4. Найдите все записи с ценой не 0.99 и с метками AlbumId 227 и 261, исключите GenreId с меткой 19
5. Найдите названия треков с длиной более 25000 с метками AlbumId не 220, 221, 227, 245, 250.

In [16]:
request('''
SELECT * 
FROM tracks
WHERE Milliseconds < 10000; 
''')

TrackId                      Name  AlbumId  MediaTypeId  GenreId  \
0      168                Now Sports       18            1        4   
1      170               A Statistic       18            1        4   
2      178                     Oprah       18            1        4   
3     2461  É Uma Partida De Futebol      200            1        1   
4     3304              Commercial 1      258            1       17   

      Composer  Milliseconds   Bytes  UnitPrice  
0         None          4884  161266       0.99  
1         None          6373  211997       0.99  
2         None          6635  224313       0.99  
3  Samuel Rosa          1071   38747       0.99  
4  L. Muggerud          7941  319888       0.99

In [17]:
request('''
SELECT * 
FROM tracks
WHERE Milliseconds < 10000 AND AlbumId = 18; 
''')

TrackId         Name  AlbumId  MediaTypeId  GenreId Composer  Milliseconds  \
0      168   Now Sports       18            1        4     None          4884   
1      170  A Statistic       18            1        4     None          6373   
2      178        Oprah       18            1        4     None          6635   

    Bytes  UnitPrice  
0  161266       0.99  
1  211997       0.99  
2  224313       0.99

In [18]:
request('''
SELECT * 
FROM tracks
WHERE Composer = 'Samuel Rosa'; 
''')

TrackId                      Name  AlbumId  MediaTypeId  GenreId  \
0      2461  É Uma Partida De Futebol      200            1        1   
1      2462            Eu Disse A Ela      200            1        1   
2      2463               Zé Trindade      200            1        1   
3      2464           Garota Nacional      200            1        1   
4      2465                   Tão Seu      200            1        1   
5      2466                 Sem Terra      200            1        1   
6      2467               Os Exilados      200            1        1   
7      2468           Um Dia Qualquer      200            1        1   
8      2469                Los Pretos      200            1        1   
9      2470            Sul Da América      200            1        1   
10     2471                    Poconé      200            1        1   

       Composer  Milliseconds     Bytes  UnitPrice  
0   Samuel Rosa          1071     38747       0.99  
1   Samuel Rosa        254223   8479463       0.99  
2   Samuel Rosa        247954   8331310       0.99  
3   Samuel Rosa        317492  10511239       0.99  
4   Samuel Rosa        243748   8133126       0.99  
5   Samuel Rosa        279353   9196411       0.99  
6   Samuel Rosa        245551   8222095       0.99  
7   Samuel Rosa        292414   9805570       0.99  
8   Samuel Rosa        239229   8025667       0.99  
9   Samuel Rosa        254928   8484871       0.99  
10  Samuel Rosa        318406  10771610       0.99

In [19]:
request('''
SELECT * 
FROM tracks
WHERE UnitPrice != 0.99 AND AlbumId = 227 OR AlbumId = 261 AND GenreId != 19;
''')

TrackId                                  Name  AlbumId  MediaTypeId  \
0      2820                Occupation / Precipice      227            3   
1      2821                         Exodus, Pt. 1      227            3   
2      2822                         Exodus, Pt. 2      227            3   
3      2823                         Collaborators      227            3   
4      2824                                  Torn      227            3   
5      2825                A Measure of Salvation      227            3   
6      2826                                  Hero      227            3   
7      2827                   Unfinished Business      227            3   
8      2828                           The Passage      227            3   
9      2829                    The Eye of Jupiter      227            3   
10     2830                               Rapture      227            3   
11     2831  Taking a Break from All Your Worries      227            3   
12     2832                        The Woman King      227            3   
13     2833                     A Day In the Life      227            3   
14     2834                           Dirty Hands      227            3   
15     2835                             Maelstrom      227            3   
16     2836                    The Son Also Rises      227            3   
17     2837                     Crossroads, Pt. 1      227            3   
18     2838                     Crossroads, Pt. 2      227            3   
19     3337             Past, Present, and Future      261            3   
20     3338              The Beginning of the End      261            3   
21     3339                 LOST Season 4 Trailer      261            3   
22     3340                          LOST In 8:15      261            3   
23     3341                        Confirmed Dead      261            3   
24     3342                         The Economist      261            3   
25     3344                          The Constant      261            3   
26     3345                       The Other Woman      261            3   
27     3348           The Shape of Things to Come      261            3   
28     3360              Something Nice Back Home      261            3   
29     3361                           Cabin Fever      261            3   
30     3362     There's No Place Like Home, Pt. 1      261            3   
31     3363     There's No Place Like Home, Pt. 2      261            3   
32     3364     There's No Place Like Home, Pt. 3      261            3   

    GenreId Composer  Milliseconds       Bytes  UnitPrice  
0        19     None       5286953  1054423946       1.99  
1        19     None       2621708   475079441       1.99  
2        19     None       2618000   466820021       1.99  
3        19     None       2626626   483484911       1.99  
4        19     None       2631291   495262585       1.99  
5        18     None       2563938   489715554       1.99  
6        18     None       2713755   506896959       1.99  
7        18     None       2622038   528499160       1.99  
8        18     None       2623875   490375760       1.99  
9        18     None       2618750   517909587       1.99  
10       18     None       2624541   508406153       1.99  
11       18     None       2624207   492700163       1.99  
12       18     None       2626376   552893447       1.99  
13       18     None       2620245   462818231       1.99  
14       18     None       2627961   537648614       1.99  
15       18     None       2622372   514154275       1.99  
16       18     None       2621830   499258498       1.99  
17       20     None       2622622   486233524       1.99  
18       20     None       2869953   497335706       1.99  
19       21     None       2492867   490796184       1.99  
20       21     None       2611903   526865050       1.99  
21       21     None        112712    20831818       1.99  
22       21     None        497163    98460675       1.99  
23       21  

In [73]:
request('''
SELECT * 
FROM tracks
WHERE Milliseconds = 25000 AND AlbumId != 220 OR AlbumId != 221 OR AlbumId != 227 OR AlbumId != 245 OR AlbumId != 250; 
''')

TrackId                                               Name  AlbumId  \
0           1            For Those About To Rock (We Salute You)        1   
1           2                                  Balls to the Wall        2   
2           3                                    Fast As a Shark        3   
3           4                                  Restless and Wild        3   
4           5                               Princess of the Dawn        3   
...       ...                                                ...      ...   
3498     3499  Pini Di Roma (Pinien Von Rom) \ I Pini Della V...      343   
3499     3500  String Quartet No. 12 in C Minor, D. 703 "Quar...      344   
3500     3501               L'orfeo, Act 3, Sinfonia (Orchestra)      345   
3501     3502  Quintet for Horn, Violin, 2 Violas, and Cello ...      346   
3502     3503                                      Koyaanisqatsi      347   

      MediaTypeId  GenreId                                           Composer  \
0               1        1          Angus Young, Malcolm Young, Brian Johnson   
1               2        1                                               None   
2               2        1  F. Baltes, S. Kaufman, U. Dirkscneider & W. Ho...   
3               2        1  F. Baltes, R.A. Smith-Diesel, S. Kaufman, U. D...   
4               2        1                         Deaffy & R.A. Smith-Diesel   
...           ...      ...                                                ...   
3498            2       24                                               None   
3499            2       24                                     Franz Schubert   
3500            2       24                                 Claudio Monteverdi   
3501            2       24                            Wolfgang Amadeus Mozart   
3502            2       10                                       Philip Glass   

      Milliseconds     Bytes  UnitPrice  
0           343719  11170334       0.99  
1           342562   5510424       0.99  
2           230619   3990994       0.99  
3           252051   4331779       0.99  
4           375418   6290521       0.99  
...            ...       ...        ...  
3498        286741   4718950       0.99  
3499        139200   2283131       0.99  
3500         66639   1189062       0.99  
3501        221331   3665114       0.99  
3502        206005   3305164       0.99  

[3503 rows x 9 columns]

Найдите все записи с AlbumId = 1, 10, 20 ,30 ,40

In [21]:
request('''
SELECT * 
FROM tracks
WHERE (AlbumId IN (1, 10, 20, 30, 40))
''')

TrackId                                     Name  AlbumId  MediaTypeId  \
0         1  For Those About To Rock (We Salute You)        1            1   
1         6                    Put The Finger On You        1            1   
2         7                          Let's Get It Up        1            1   
3         8                         Inject The Venom        1            1   
4         9                               Snowballed        1            1   
..      ...                                      ...      ...          ...   
56      496                           Living On Love       40            1   
57      497                            Midnight Blue       40            1   
58      498                           Too Many Tears       40            1   
59      499                          Don't Lie To Me       40            1   
60      500                      Wherever You May Go       40            1   

    GenreId                                   Composer  Milliseconds  \
0         1  Angus Young, Malcolm Young, Brian Johnson        343719   
1         1  Angus Young, Malcolm Young, Brian Johnson        205662   
2         1  Angus Young, Malcolm Young, Brian Johnson        233926   
3         1  Angus Young, Malcolm Young, Brian Johnson        210834   
4         1  Angus Young, Malcolm Young, Brian Johnson        203102   
..      ...                                        ...           ...   
56        1           Bossi/David Coverdale/Earl Slick        391549   
57        1                 David Coverdale/Earl Slick        298631   
58        1          Adrian Vanderberg/David Coverdale        359497   
59        1                 David Coverdale/Earl Slick        283585   
60        1                            David Coverdale        239699   

       Bytes  UnitPrice  
0   11170334       0.99  
1    6713451       0.99  
2    7636561       0.99  
3    6852860       0.99  
4    6599424       0.99  
..       ...        ...  
56  12785876       0.99  
57   9750990       0.99  
58  11810238       0.99  
59   9288007       0.99  
60   7803074       0.99  

[61 rows x 9 columns]

Задание
1. Найдите название треков, в которых принимал участие Carlos Santana с длиной более 329000 и не из альбома с id 197.

In [26]:
request('''
SELECT * 
FROM tracks
WHERE (composer LIKE '%Carlos Santana%') AND Milliseconds > 329000 AND AlbumId != 197; 
''')

TrackId             Name  AlbumId  MediaTypeId  GenreId  \
0      571  Love Of My Life       46            1        1   
1      577            Migra       46            1        1   
2      582      The Calling       46            1        1   

                               Composer  Milliseconds     Bytes  UnitPrice  
0        Carlos Santana & Dave Matthews        347820  11634337       0.99  
1  R. Taha, Carlos Santana & T. Lindsay        329064  10963305       0.99  
2          Carlos Santana & C. Thompson        747755  24703884       0.99

Задание
1. Найдите все заказы, оформленые в 2012 году.
2. Найдите все заказы, оформленные первого числа каждого месяца

In [30]:
request('''
SELECT invoiceDate, STRFTIME("%Y", invoiceDate) AS year
FROM invoices
WHERE Year = "2012";
''')

InvoiceDate  year
0   2012-01-01 00:00:00  2012
1   2012-01-09 00:00:00  2012
2   2012-01-22 00:00:00  2012
3   2012-01-22 00:00:00  2012
4   2012-01-23 00:00:00  2012
..                  ...   ...
78  2012-12-15 00:00:00  2012
79  2012-12-28 00:00:00  2012
80  2012-12-28 00:00:00  2012
81  2012-12-29 00:00:00  2012
82  2012-12-30 00:00:00  2012

[83 rows x 2 columns]

In [31]:
request('''
SELECT InvoiceDate, STRFTIME("%d", invoiceDate) 
FROM invoices
WHERE STRFTIME("%d", invoiceDate) = '01';
''')

InvoiceDate STRFTIME("%d", invoiceDate)
0   2009-01-01 00:00:00                          01
1   2009-02-01 00:00:00                          01
2   2009-02-01 00:00:00                          01
3   2010-10-01 00:00:00                          01
4   2010-11-01 00:00:00                          01
5   2011-12-01 00:00:00                          01
6   2012-01-01 00:00:00                          01
7   2012-02-01 00:00:00                          01
8   2012-10-01 00:00:00                          01
9   2012-11-01 00:00:00                          01
10  2013-03-01 00:00:00                          01
11  2013-04-01 00:00:00                          01
12  2013-05-01 00:00:00                          01
13  2013-05-01 00:00:00                          01
14  2013-06-01 00:00:00                          01
15  2013-06-01 00:00:00                          01

**Задания на срезы данных**

1. Найдите адреса всех заказов в Berlin
2. Найдите InvoiceId заказов из Канады, США, и Германии
3.  Найдите InvoiceId заказов из Канады, США, и Германии на сумму не менее 5.
4.  Найдите BillingPostalCode всех заказов за 2013 год в США.
5. Найдите все записи в которых есть  пропуски хотя бы в одном из полей  BillingCity, BillingState, BillingCountry
6. Найдите все заказы, сформированные весной (за все года) на сумму не менее 8

In [33]:
request('''
SELECT *
FROM invoices
WHERE BillingCity IS 'Berlin'
''')

InvoiceId  CustomerId          InvoiceDate       BillingAddress  \
0           7          38  2009-02-01 00:00:00  Barbarossastraße 19   
1          29          36  2009-05-05 00:00:00   Tauentzienstraße 8   
2          30          38  2009-05-06 00:00:00  Barbarossastraße 19   
3          40          36  2009-06-15 00:00:00   Tauentzienstraße 8   
4          52          38  2009-08-08 00:00:00  Barbarossastraße 19   
5          95          36  2010-02-13 00:00:00   Tauentzienstraße 8   
6         104          38  2010-03-29 00:00:00  Barbarossastraße 19   
7         224          36  2011-09-20 00:00:00   Tauentzienstraße 8   
8         225          38  2011-09-20 00:00:00  Barbarossastraße 19   
9         236          38  2011-10-31 00:00:00  Barbarossastraße 19   
10        247          36  2011-12-23 00:00:00   Tauentzienstraße 8   
11        269          36  2012-03-26 00:00:00   Tauentzienstraße 8   
12        291          38  2012-06-30 00:00:00  Barbarossastraße 19   
13        321          36  2012-11-14 00:00:00   Tauentzienstraße 8   

   BillingCity BillingState BillingCountry BillingPostalCode  Total  
0       Berlin         None        Germany             10779   1.98  
1       Berlin         None        Germany             10789   1.98  
2       Berlin         None        Germany             10779   3.96  
3       Berlin         None        Germany             10789  13.86  
4       Berlin         None        Germany             10779   5.94  
5       Berlin         None        Germany             10789   8.91  
6       Berlin         None        Germany             10779   0.99  
7       Berlin         None        Germany             10789   1.98  
8       Berlin         None        Germany             10779   1.98  
9       Berlin         None        Germany             10779  13.86  
10      Berlin         None        Germany             10789   3.96  
11      Berlin         None        Germany             10789   5.94  
12      Berlin         None        Germany             10779   8.91  
13      Berlin         None        Germany             10789   0.99

In [34]:
request('''
SELECT *
FROM invoices
WHERE BillingCountry = 'Canada' OR BillingCountry = 'USA' OR BillingCountry = 'Germany';
''')

InvoiceId  CustomerId          InvoiceDate           BillingAddress  \
0            1           2  2009-01-01 00:00:00  Theodor-Heuss-Straße 34   
1            4          14  2009-01-06 00:00:00           8210 111 ST NW   
2            5          23  2009-01-11 00:00:00          69 Salem Street   
3            6          37  2009-01-19 00:00:00         Berger Straße 10   
4            7          38  2009-02-01 00:00:00      Barbarossastraße 19   
..         ...         ...                  ...                      ...   
170        405          20  2013-11-21 00:00:00     541 Del Medio Avenue   
171        406          21  2013-12-04 00:00:00         801 W 4th Street   
172        407          23  2013-12-04 00:00:00          69 Salem Street   
173        408          25  2013-12-05 00:00:00    319 N. Frances Street   
174        409          29  2013-12-06 00:00:00   796 Dundas Street West   

       BillingCity BillingState BillingCountry BillingPostalCode  Total  
0        Stuttgart         None        Germany             70174   1.98  
1         Edmonton           AB         Canada           T6G 2C7   8.91  
2           Boston           MA            USA              2113  13.86  
3        Frankfurt         None        Germany             60316   0.99  
4           Berlin         None        Germany             10779   1.98  
..             ...          ...            ...               ...    ...  
170  Mountain View           CA            USA         94040-111   0.99  
171           Reno           NV            USA             89503   1.98  
172         Boston           MA            USA              2113   1.98  
173        Madison           WI            USA             53703   3.96  
174        Toronto           ON         Canada           M6J 1V1   5.94  

[175 rows x 9 columns]

In [35]:
request('''
SELECT *
FROM invoices
WHERE (BillingCountry = 'Canada' OR BillingCountry = 'USA' OR BillingCountry = 'Germany') AND Total >= 5;
''')

InvoiceId  CustomerId          InvoiceDate           BillingAddress  \
0           4          14  2009-01-06 00:00:00           8210 111 ST NW   
1           5          23  2009-01-11 00:00:00          69 Salem Street   
2          12           2  2009-02-11 00:00:00  Theodor-Heuss-Straße 34   
3          17          25  2009-03-06 00:00:00    319 N. Frances Street   
4          18          31  2009-03-09 00:00:00    194A Chain Lake Drive   
..        ...         ...                  ...                      ...   
71        376          31  2013-07-12 00:00:00    194A Chain Lake Drive   
72        388          33  2013-09-04 00:00:00           5112 48 Street   
73        396          18  2013-10-08 00:00:00             627 Broadway   
74        397          27  2013-10-13 00:00:00          1033 N Park Ave   
75        409          29  2013-12-06 00:00:00   796 Dundas Street West   

    BillingCity BillingState BillingCountry BillingPostalCode  Total  
0      Edmonton           AB         Canada           T6G 2C7   8.91  
1        Boston           MA            USA              2113  13.86  
2     Stuttgart         None        Germany             70174  13.86  
3       Madison           WI            USA             53703   5.94  
4       Halifax           NS         Canada           B3S 1C5   8.91  
..          ...          ...            ...               ...    ...  
71      Halifax           NS         Canada           B3S 1C5  13.86  
72  Yellowknife           NT         Canada           X1A 1N6   5.94  
73     New York           NY            USA        10012-2612   8.91  
74       Tucson           AZ            USA             85719  13.86  
75      Toronto           ON         Canada           M6J 1V1   5.94  

[76 rows x 9 columns]

In [36]:
request('''
SELECT invoiceDate, STRFTIME("%Y", invoiceDate) AS year, BillingPostalCode
FROM invoices
WHERE Year = "2013";
''')

InvoiceDate  year BillingPostalCode
0   2013-01-02 00:00:00  2013           K2P 1L7
1   2013-01-07 00:00:00  2013             75009
2   2013-01-15 00:00:00  2013          SW1V 3EN
3   2013-01-28 00:00:00  2013           EH4 1HH
4   2013-01-28 00:00:00  2013              1106
..                  ...   ...               ...
75  2013-12-05 00:00:00  2013             53703
76  2013-12-06 00:00:00  2013           M6J 1V1
77  2013-12-09 00:00:00  2013              None
78  2013-12-14 00:00:00  2013             00530
79  2013-12-22 00:00:00  2013            110017

[80 rows x 3 columns]

In [37]:
request('''
SELECT *
FROM invoices
WHERE BillingState IS NULL OR BillingCity IS NULL OR BillingCountry IS NULL;
''')

InvoiceId  CustomerId          InvoiceDate  \
0            1           2  2009-01-01 00:00:00   
1            2           4  2009-01-02 00:00:00   
2            3           8  2009-01-03 00:00:00   
3            6          37  2009-01-19 00:00:00   
4            7          38  2009-02-01 00:00:00   
..         ...         ...                  ...   
197        403          56  2013-11-08 00:00:00   
198        404           6  2013-11-13 00:00:00   
199        410          35  2013-12-09 00:00:00   
200        411          44  2013-12-14 00:00:00   
201        412          58  2013-12-22 00:00:00   

                               BillingAddress   BillingCity BillingState  \
0                     Theodor-Heuss-Straße 34     Stuttgart         None   
1                            Ullevålsveien 14          Oslo         None   
2                             Grétrystraat 63      Brussels         None   
3                            Berger Straße 10     Frankfurt         None   
4                         Barbarossastraße 19        Berlin         None   
..                                        ...           ...          ...   
197                        307 Macacha Güemes  Buenos Aires         None   
198                             Rilská 3174/6        Prague         None   
199  Rua dos Campeões Europeus de Viena, 4350         Porto         None   
200                           Porthaninkatu 9      Helsinki         None   
201                       12,Community Centre         Delhi         None   

     BillingCountry BillingPostalCode  Total  
0           Germany             70174   1.98  
1            Norway              0171   3.96  
2           Belgium              1000   5.94  
3           Germany             60316   0.99  
4           Germany             10779   1.98  
..              ...               ...    ...  
197       Argentina              1106   8.91  
198  Czech Republic             14300  25.86  
199        Portugal              None   8.91  
200         Finland             00530  13.86  
201           India            110017   1.99  

[202 rows x 9 columns]

In [38]:
request('''
SELECT InvoiceDate, STRFTIME("%d", invoiceDate)
FROM invoices
WHERE (STRFTIME("%d", invoiceDate) = '03' OR STRFTIME("%d", invoiceDate) = '04' OR STRFTIME("%d", invoiceDate) = '05') AND Total >= 8
''')

InvoiceDate STRFTIME("%d", invoiceDate)
0  2012-03-03 00:00:00                          03
1  2012-04-03 00:00:00                          03
2  2012-05-04 00:00:00                          04
3  2012-06-04 00:00:00                          04
4  2012-07-05 00:00:00                          05
5  2012-08-05 00:00:00                          05
6  2012-09-05 00:00:00                          05
7  2013-03-05 00:00:00                          05
8  2013-04-05 00:00:00                          05

**Категоризация данных**

In [39]:
request('''
SELECT total, CASE 
WHEN total < 5 THEN 'low'
WHEN total >=5 THEN 'high'
END
FROM invoices

''')

Total CASE \nWHEN total < 5 THEN 'low'\nWHEN total >=5 THEN 'high'\nEND
0     1.98                                                low               
1     3.96                                                low               
2     5.94                                               high               
3     8.91                                               high               
4    13.86                                               high               
..     ...                                                ...               
407   3.96                                                low               
408   5.94                                               high               
409   8.91                                               high               
410  13.86                                               high               
411   1.99                                                low               

[412 rows x 2 columns]

# Агрегирующие функции

Задание
1. Найдите все записи за сентябрь и октябрь.
2. Найдите сумму заказов дополнительно исключите из запроса InvoiceId 58, 59 60
3. Добавьте число уникальных пользователей (CustomerId) и среднее значение заказов.
4. Найдите сумму заказов и среднее значение заказов из Германии.

In [44]:
request('''
SELECT InvoiceDate, STRFTIME("%m", invoiceDate)
FROM invoices
WHERE STRFTIME("%m", InvoiceDate) = '09' OR STRFTIME("%m", InvoiceDate) = '10';
''')

InvoiceDate STRFTIME("%m", invoiceDate)
0   2009-09-06 00:00:00                          09
1   2009-09-06 00:00:00                          09
2   2009-09-07 00:00:00                          09
3   2009-09-08 00:00:00                          09
4   2009-09-11 00:00:00                          09
..                  ...                         ...
63  2013-10-04 00:00:00                          10
64  2013-10-05 00:00:00                          10
65  2013-10-08 00:00:00                          10
66  2013-10-13 00:00:00                          10
67  2013-10-21 00:00:00                          10

[68 rows x 2 columns]

In [45]:
request('''
SELECT SUM(total) AS sum
FROM invoices
WHERE InvoiceId != '58' OR InvoiceId != '59' OR InvoiceId != '60';
''')

sum
0  2328.6

In [46]:
request('''
SELECT COUNT(DISTINCT CustomerId) AS CustomerId1, 
ROUND(AVG(total), 2) AS avg
FROM invoices
''')

CustomerId1   avg
0           59  5.65

# Группировка

Задание
1. Найдите сумму заказов, число заказов и средний чек для каждого города в Германии.
2. Найдите сумму заказов, сгруппировав данные по годам.
3. Категоризируйте данные по двум группам (low, если заказ меньше 5 и high если больше 5). Найдите число заказов в каждой группе

In [48]:
request('''
SELECT BillingCity, Count(total), SUM(total), AVG(total)
FROM invoices WHERE BillingCountry IS 'Germany'
GROUP BY BillingCity;
''')

BillingCity  Count(total)  SUM(total)  AVG(total)
0      Berlin            14       75.24    5.374286
1   Frankfurt             7       43.62    6.231429
2   Stuttgart             7       37.62    5.374286

In [49]:
request('''
SELECT InvoiceDate, STRFTIME("%Y", invoiceDate) AS year, SUM(total)
FROM invoices
GROUP BY year;
''')

InvoiceDate  year  SUM(total)
0  2009-01-01 00:00:00  2009      449.46
1  2010-01-08 00:00:00  2010      481.45
2  2011-01-02 00:00:00  2011      469.58
3  2012-01-01 00:00:00  2012      477.53
4  2013-01-02 00:00:00  2013      450.58

In [50]:
request('''
SELECT COUNT(total), CASE
WHEN total < 5 THEN 'low'
WHEN total >=5 THEN 'high'
END
FROM invoices
GROUP BY CASE
WHEN total < 5 THEN 'low'
WHEN total >=5 THEN 'high'
END

''')

COUNT(total)  \
0           179   
1           233   

  CASE\nWHEN total < 5 THEN 'low'\nWHEN total >=5 THEN 'high'\nEND  
0                                               high                
1                                                low

**Сортировка**

Задание
1. Из таблицы invoices найдите число уникальных городов для каждой страны, отсортируйте по убыванию.
2. Сгруппируйте данные по двум полям: страна и город. Найдите число и сумму заказов для каждой пары, отсортируйте по числу заказов.  
3. Добавте срез данных: сумма заказов больше 40 и исключите 2009 год.

In [54]:
request('''
SELECT BillingCountry, COUNT(DISTINCT BillingCity) as uniq_city
FROM invoices
GROUP BY BillingCountry
ORDER BY SUM(total) DESC

''')

BillingCountry  uniq_city
0              USA         12
1           Canada          8
2           France          4
3           Brazil          4
4          Germany          3
5   United Kingdom          2
6   Czech Republic          1
7         Portugal          2
8            India          2
9            Chile          1
10         Ireland          1
11         Hungary          1
12         Austria          1
13         Finland          1
14     Netherlands          1
15          Norway          1
16          Sweden          1
17          Poland          1
18           Italy          1
19         Denmark          1
20       Australia          1
21       Argentina          1
22           Spain          1
23         Belgium          1

In [55]:
request('''
SELECT BillingCountry, BillingCity, SUM(total), COUNT(total)
FROM invoices
GROUP BY BillingCountry, BillingCity
ORDER BY COUNT(total) DESC

''')

BillingCountry          BillingCity  SUM(total)  COUNT(total)
0           Brazil            São Paulo       75.24            14
1   Czech Republic               Prague       90.24            14
2           France                Paris       77.24            14
3          Germany               Berlin       75.24            14
4              USA        Mountain View       77.24            14
5   United Kingdom               London       75.24            14
6        Argentina         Buenos Aires       37.62             7
7        Australia               Sidney       37.62             7
8          Austria               Vienne       42.62             7
9          Belgium             Brussels       37.62             7
10          Brazil             Brasília       37.62             7
11          Brazil       Rio de Janeiro       37.62             7
12          Brazil  São José dos Campos       39.62             7
13          Canada             Edmonton       37.62             7
14          Canada              Halifax       37.62             7
15          Canada             Montréal       39.62             7
16          Canada               Ottawa       37.62             7
17          Canada              Toronto       37.62             7
18          Canada            Vancouver       38.62             7
19          Canada             Winnipeg       37.62             7
20          Canada          Yellowknife       37.62             7
21           Chile             Santiago       46.62             7
22         Denmark           Copenhagen       37.62             7
23         Finland             Helsinki       41.62             7
24          France             Bordeaux       39.62             7
25          France                Dijon       40.62             7
26          France                 Lyon       37.62             7
27         Germany            Frankfurt       43.62             7
28         Germany            Stuttgart       37.62             7
29         Hungary             Budapest       45.62             7
30           India                Delhi       38.62             7
31         Ireland               Dublin       45.62             7
32           Italy                 Rome       37.62             7
33     Netherlands            Amsterdam       40.62             7
34          Norway                 Oslo       39.62             7
35          Poland               Warsaw       37.62             7
36        Portugal               Lisbon       39.62             7
37        Portugal                Porto       37.62             7
38           Spain               Madrid       37.62             7
39          Sweden            Stockholm       38.62             7
40             USA               Boston       37.62             7
41             USA              Chicago       43.62             7
42             USA            Cupertino       38.62             7
43             USA           Fort Worth       47.62             7
44             USA              Madison       42.62             7
45             USA             New York       37.62             7
46             USA              Orlando       39.62             7
47             USA              Redmond       39.62             7
48             USA                 Reno       37.62             7
49             USA       Salt Lake City       43.62             7
50             USA               Tucson       37.62             7
51  United Kingdom           Edinburgh        37.62             7
52           India            Bangalore       36.64             6

In [56]:
request('''
SELECT BillingCountry, BillingCity, SUM(total), COUNT(total), STRFTIME("%Y", invoiceDate) AS year
FROM invoices
GROUP BY BillingCountry, BillingCity
HAVING SUM(total) > 40 AND year != '2009'
ORDER BY COUNT(total) DESC
''')

BillingCountry BillingCity  SUM(total)  COUNT(total)  year
0         France       Dijon       40.62             7  2010
1        Hungary    Budapest       45.62             7  2010
2            USA     Chicago       43.62             7  2010

# Псведонимы

In [57]:
request('''
SELECT BillingCountry, SUM(total) AS total_sum, COUNT (DISTINCT  BillingCity) as unique_city 
FROM invoices
GROUP BY BillingCountry
HAVING total_sum > 90
ORDER BY total_sum DESC

''')

BillingCountry  total_sum  unique_city
0             USA     523.06           12
1          Canada     303.96            8
2          France     195.10            4
3          Brazil     190.10            4
4         Germany     156.48            3
5  United Kingdom     112.86            2
6  Czech Republic      90.24            1

# Объединение таблиц 

Задание.
1. Добавьте в получившуюся выше таблицу информацию о жанрах.
2. В каком жанре суммарная продолжительность треков больше? Отсортируйте по убыванию, оставьте топ-5
3. Найти все альбомы в базе данных и для каждого альбома вывести название альбома и имя исполнителя.

In [61]:
request('''
SELECT *
FROM tracks AS t 
INNER JOIN albums AS a ON t.albumId = a.albumId
INNER JOIN genres AS g ON t.genreId = g.genreId
''')

TrackId                                               Name  AlbumId  \
0           1            For Those About To Rock (We Salute You)        1   
1           2                                  Balls to the Wall        2   
2           3                                    Fast As a Shark        3   
3           4                                  Restless and Wild        3   
4           5                               Princess of the Dawn        3   
...       ...                                                ...      ...   
3498     3499  Pini Di Roma (Pinien Von Rom) \ I Pini Della V...      343   
3499     3500  String Quartet No. 12 in C Minor, D. 703 "Quar...      344   
3500     3501               L'orfeo, Act 3, Sinfonia (Orchestra)      345   
3501     3502  Quintet for Horn, Violin, 2 Violas, and Cello ...      346   
3502     3451  Die Zauberflöte, K.620: "Der Hölle Rache Kocht...      317   

      MediaTypeId  GenreId                                           Composer  \
0               1        1          Angus Young, Malcolm Young, Brian Johnson   
1               2        1                                               None   
2               2        1  F. Baltes, S. Kaufman, U. Dirkscneider & W. Ho...   
3               2        1  F. Baltes, R.A. Smith-Diesel, S. Kaufman, U. D...   
4               2        1                         Deaffy & R.A. Smith-Diesel   
...           ...      ...                                                ...   
3498            2       24                                               None   
3499            2       24                                     Franz Schubert   
3500            2       24                                 Claudio Monteverdi   
3501            2       24                            Wolfgang Amadeus Mozart   
3502            2       25                            Wolfgang Amadeus Mozart   

      Milliseconds     Bytes  UnitPrice  AlbumId  \
0           343719  11170334       0.99        1   
1           342562   5510424       0.99        2   
2           230619   3990994       0.99        3   
3           252051   4331779       0.99        3   
4           375418   6290521       0.99        3   
...            ...       ...        ...      ...   
3498        286741   4718950       0.99      343   
3499        139200   2283131       0.99      344   
3500         66639   1189062       0.99      345   
3501        221331   3665114       0.99      346   
3502        174813   2861468       0.99      317   

                                                  Title  ArtistId  GenreId  \
0                 For Those About To Rock We Salute You         1        1   
1                                     Balls to the Wall         2        1   
2                                     Restless and Wild         2        1   
3                                     Restless and Wild         2        1   
4                                     Restless and Wild         2        1   
...                                                 ...       ...      ...   
3498                             Respighi:Pines of Rome       226       24   
3499  Schubert: The Late String Quartets & String Qu...       272       24   
3500                                Monteverdi: L'Orfeo       273       24   
3501                              Mozart: Chamber Music       274       24   
3502                          Mozart Gala: Famous Arias       249       25   

           Name  
0          Rock  
1          Rock  
2          Rock  
3          Rock  
4          Rock  
...         ...  
3498  Classical  
3499  Classical  
3500  Classical  
3501  Classical  
3502      Opera  

[3503 rows x 14 columns]

In [62]:
request('''
SELECT *
FROM tracks AS t
INNER JOIN genres AS g ON t.genreId = g.genreId 
''')

TrackId                                               Name  AlbumId  \
0           1            For Those About To Rock (We Salute You)        1   
1           2                                  Balls to the Wall        2   
2           3                                    Fast As a Shark        3   
3           4                                  Restless and Wild        3   
4           5                               Princess of the Dawn        3   
...       ...                                                ...      ...   
3498     3499  Pini Di Roma (Pinien Von Rom) \ I Pini Della V...      343   
3499     3500  String Quartet No. 12 in C Minor, D. 703 "Quar...      344   
3500     3501               L'orfeo, Act 3, Sinfonia (Orchestra)      345   
3501     3502  Quintet for Horn, Violin, 2 Violas, and Cello ...      346   
3502     3451  Die Zauberflöte, K.620: "Der Hölle Rache Kocht...      317   

      MediaTypeId  GenreId                                           Composer  \
0               1        1          Angus Young, Malcolm Young, Brian Johnson   
1               2        1                                               None   
2               2        1  F. Baltes, S. Kaufman, U. Dirkscneider & W. Ho...   
3               2        1  F. Baltes, R.A. Smith-Diesel, S. Kaufman, U. D...   
4               2        1                         Deaffy & R.A. Smith-Diesel   
...           ...      ...                                                ...   
3498            2       24                                               None   
3499            2       24                                     Franz Schubert   
3500            2       24                                 Claudio Monteverdi   
3501            2       24                            Wolfgang Amadeus Mozart   
3502            2       25                            Wolfgang Amadeus Mozart   

      Milliseconds     Bytes  UnitPrice  GenreId       Name  
0           343719  11170334       0.99        1       Rock  
1           342562   5510424       0.99        1       Rock  
2           230619   3990994       0.99        1       Rock  
3           252051   4331779       0.99        1       Rock  
4           375418   6290521       0.99        1       Rock  
...            ...       ...        ...      ...        ...  
3498        286741   4718950       0.99       24  Classical  
3499        139200   2283131       0.99       24  Classical  
3500         66639   1189062       0.99       24  Classical  
3501        221331   3665114       0.99       24  Classical  
3502        174813   2861468       0.99       25      Opera  

[3503 rows x 11 columns]

In [63]:
request('''
SELECT g.name, SUM(Milliseconds)
FROM tracks AS t
INNER JOIN genres AS g ON t.genreId = g.genreId 
GROUP BY g.Name
ORDER BY SUM(Milliseconds) DESC
LIMIT 5
''')

Name  SUM(Milliseconds)
0      Rock          368231326
1  TV Shows          199488815
2     Drama          164818162
3     Latin          134825513
4     Metal          115846292

In [64]:
request('''
SELECT DISTINCT Title, ar.Name
FROM tracks AS t 
INNER JOIN albums AS a ON t.albumId = a.albumId
INNER JOIN artists AS ar ON a.artistId = ar.artistId
''')

Title  \
0                For Those About To Rock We Salute You   
1                                    Balls to the Wall   
2                                    Restless and Wild   
3                                    Let There Be Rock   
4                                             Big Ones   
..                                                 ...   
342                             Respighi:Pines of Rome   
343  Schubert: The Late String Quartets & String Qu...   
344                                Monteverdi: L'Orfeo   
345                              Mozart: Chamber Music   
346  Koyaanisqatsi (Soundtrack from the Motion Pict...   

                                                  Name  
0                                                AC/DC  
1                                               Accept  
2                                               Accept  
3                                                AC/DC  
4                                            Aerosmith  
..                                                 ...  
342                                     Eugene Ormandy  
343                             Emerson String Quartet  
344  C. Monteverdi, Nigel Rogers - Chiaroscuro; Lon...  
345                                      Nash Ensemble  
346                              Philip Glass Ensemble  

[347 rows x 2 columns]

Задание.<br>
Найдите топ-5 клиентов(фамилия и имя) по среднему чеку заказа. Для этого присоедините таблицу customers к таблице invoice.

In [65]:
request('''
SELECT FirstName, LastName, AVG(UnitPrice)
FROM invoices AS i
INNER JOIN invoice_items AS ii ON i.InvoiceId = ii.InvoiceId
INNER JOIN customers AS c ON i.CustomerId = c.CustomerId
GROUP BY c.FirstName, c.LastName
ORDER BY AVG(UnitPrice) DESC
LIMIT 5
''')

FirstName    LastName  AVG(UnitPrice)
0    Helena        Holý        1.305789
1   Richard  Cunningham        1.253158
2      Luis       Rojas        1.226842
3      Hugh    O'Reilly        1.200526
4  Ladislav      Kovács        1.200526

Задание:
У какого исполнителя больше все выпущено альбомов?

In [67]:
request('''
SELECT DISTINCT ar.Name, Title
FROM tracks AS t 
INNER JOIN albums AS a ON t.albumId = a.albumId
INNER JOIN artists AS ar ON a.artistId = ar.artistId
''')

Name  \
0                                                AC/DC   
1                                               Accept   
2                                               Accept   
3                                                AC/DC   
4                                            Aerosmith   
..                                                 ...   
342                                     Eugene Ormandy   
343                             Emerson String Quartet   
344  C. Monteverdi, Nigel Rogers - Chiaroscuro; Lon...   
345                                      Nash Ensemble   
346                              Philip Glass Ensemble   

                                                 Title  
0                For Those About To Rock We Salute You  
1                                    Balls to the Wall  
2                                    Restless and Wild  
3                                    Let There Be Rock  
4                                             Big Ones  
..                                                 ...  
342                             Respighi:Pines of Rome  
343  Schubert: The Late String Quartets & String Qu...  
344                                Monteverdi: L'Orfeo  
345                              Mozart: Chamber Music  
346  Koyaanisqatsi (Soundtrack from the Motion Pict...  

[347 rows x 2 columns]

In [68]:
request('''
SELECT ar.Name, COUNT(DISTINCT Title)
FROM tracks AS t 
INNER JOIN albums AS a ON t.albumId = a.albumId
INNER JOIN artists AS ar ON a.artistId = ar.artistId
GROUP BY ar.Name
ORDER BY COUNT(DISTINCT Title) DESC
LIMIT 5
''')

Name  COUNT(DISTINCT Title)
0   Iron Maiden                     21
1  Led Zeppelin                     14
2   Deep Purple                     11
3            U2                     10
4     Metallica                     10

Дополнительные вопросы

1. Вывести список всех артистов в базе данных.
2. Вывести список всех жанров музыки без повторений.
3.  Вывести список всех заказчиков, отсортированных по фамилии в алфавитном порядке.

In [69]:
request('''
SELECT DISTINCT Name
FROM artists 
''')

Name
0                                                AC/DC
1                                               Accept
2                                            Aerosmith
3                                    Alanis Morissette
4                                      Alice In Chains
..                                                 ...
270   Mela Tenenbaum, Pro Musica Prague & Richard Kapp
271                             Emerson String Quartet
272  C. Monteverdi, Nigel Rogers - Chiaroscuro; Lon...
273                                      Nash Ensemble
274                              Philip Glass Ensemble

[275 rows x 1 columns]

In [70]:
request('''
SELECT name
FROM genres
''')

Name
0                 Rock
1                 Jazz
2                Metal
3   Alternative & Punk
4        Rock And Roll
5                Blues
6                Latin
7               Reggae
8                  Pop
9           Soundtrack
10          Bossa Nova
11      Easy Listening
12         Heavy Metal
13            R&B/Soul
14   Electronica/Dance
15               World
16         Hip Hop/Rap
17     Science Fiction
18            TV Shows
19    Sci Fi & Fantasy
20               Drama
21              Comedy
22         Alternative
23           Classical
24               Opera

In [71]:
request('''
SELECT DISTINCT LastName
FROM employees
ORDER BY LastName
''')

LastName
0     Adams
1  Callahan
2   Edwards
3   Johnson
4      King
5  Mitchell
6      Park
7   Peacock